# Generated by Django 4.0 on 2021-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="YoutubeAPIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_title", models.TextField()),
                ("description", models.TextField()),
                ("publish_datetime", models.DateTimeField()),
                ("thumbnail_url", models.TextField()),
            ],
        ),
    ]
